server:
  port: 8080

spring:
  datasource:
    username: root
#    password: 123
    password: 123456
    url: jdbc:mysql://192.168.120.5:3306/oo?useUnicode=true&characterEncoding=utf-8&useSSL=true&autoReconnect=true&allowMultiQueries=true&serverTimezone=UTC
#    url: jdbc:mysql://localhost:3306/oo?useUnicode=true&characterEncoding=utf-8&useSSL=true&autoReconnect=true&allowMultiQueries=true&serverTimezone=UTC
#    url: jdbc:mysql://127.0.0.1:3306/oo?useUnicode=true&characterEncoding=utf-8&useSSL=true&autoReconnect=true&allowMultiQueries=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /**

  # Redis数据库索引（默认为0）
  redis:
    # Redis服务器地址
    host: 192.168.120.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123
    # 连接池最大连接数（使用负值表示没有限制） 默认 8
    lettuce.pool.max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
    lettuce.pool.max-wait: -1
    # 连接池中的最大空闲连接 默认 8
    lettuce.pool.max-idle: 8
    # 连接池中的最小空闲连接 默认 0
    lettuce.pool.min-idle: 0
    lettuce:
      shutdown-timeout: 0



mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.model

#showSql
logging:
  level:
    com:
      example:
        mapper: debug


thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  encoding: utf-8
  mode: html5
  servlet:
    content-type: text/html




